spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: test
      database: booklog-message
      initialization-mode: create

  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

  sql:
    init:
      platform: local
      mode: always

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: booklog-message

logging.level:
  org.hibernate.SQL: debug
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG